## USB port
port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A8007ZGn-if00-port0


##### Calibration ####
### accelerometer
accel_x_min: -277.0
accel_x_max: 281.0
accel_y_min: -263.0
accel_y_max: 284.0
accel_z_min: -272.0
accel_z_max: 263.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [48.7156, 64.3868, 96.7279]
magn_ellipsoid_transform: [[0.966446, 0.000688564, -0.00865954], [0.000688564, 0.938734, 0.0352535], [-0.00865954, 0.0352535, 0.977679]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 1.60
gyro_average_offset_y: 28.14
gyro_average_offset_z: 5.61
